[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "2ZCEiywq7CqqiNo726wDeX9croaZwBxwtExGwf4dg7s7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/murat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
