[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vote = "4kbqKAWg1wg4t7UynAVnCEmiC2eonUxZm8c61xMPR77D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/murat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
