[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace = "F2HAqgH9yVEVx1isB2wrAhC9Ruo28w48JxsWeMAASmqU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/murat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
