[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "Z82xSvKryNqCEF1VwoL6myvNCF2JgbRjsW1F9TJ8y9q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/murat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
