[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "DGzACNZ7YcnLEA8B7ZtJPt25bxXi95KXxrQXCLwvXARn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/murat/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
